/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Business.Applicant;
import Business.ApplicantDirectory;
import Business.Application;
import Business.ApplicationDirectory;
import Business.Property;
import Business.PropertyDirectory;
import javax.swing.JPanel;
import java.awt.CardLayout;


/**
 *
 * @author Ayush
 */
public class ApplicantViewApprovedPropertiesJPanel extends javax.swing.JPanel {
    private JPanel workArea;
    private ApplicantDirectory applicantDirectory;
    private Applicant applicant;
    private PropertyDirectory propertyDirectory;
    /**
     * Creates new form ViewApprovedPropertiesJPanel
     */
    public ApplicantViewApprovedPropertiesJPanel(JPanel workArea, ApplicantDirectory applicantDirectory, Applicant applicant, PropertyDirectory propertyDirectory) {
        initComponents();
                this.workArea = workArea;
        this.applicantDirectory = applicantDirectory;
        this.applicant = applicant;
        this.propertyDirectory = propertyDirectory;
        
        Boolean isApplicationApproved = false;
            
        if(propertyDirectory.isPropertyRentedTo(applicant.getApplicantID())){
            isApplicationApproved = true;
        }
        
        
        if(isApplicationApproved) {
            Property property = propertyDirectory.searchPropertyByApplicationId(applicant.getApplicantID());
            lblPropertyNameValue.setText(property.getName());
            lblPropertyAddressValue.setText(property.getAddress());
            lblCityValue.setText(property.getCity());
            lblStateValue.setText(property.getState());
            lblPincodeValue.setText(property.getPincode());
        }
        else{
            lblViewApprovedProperty.setText("You do not have approved properties.");
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblViewApprovedProperty = new javax.swing.JLabel();
        lblPropertyNameValue = new javax.swing.JLabel();
        lblPropertyAddressValue = new javax.swing.JLabel();
        lblCityValue = new javax.swing.JLabel();
        lblStateValue = new javax.swing.JLabel();
        lblPincodeValue = new javax.swing.JLabel();
        lblPropertyName = new javax.swing.JLabel();
        lblPropertyAddress = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        lblPinCode = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(223, 223, 223));

        lblViewApprovedProperty.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        lblViewApprovedProperty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewApprovedProperty.setText("Below is your Approved Property :");

        lblPropertyNameValue.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        lblPropertyNameValue.setText("                                         ");

        lblPropertyAddressValue.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        lblPropertyAddressValue.setText("                                          ");

        lblCityValue.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        lblCityValue.setText("                                         ");

        lblStateValue.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        lblStateValue.setText("                                        ");

        lblPincodeValue.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        lblPincodeValue.setText("                                         ");

        lblPropertyName.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        lblPropertyName.setText("Property Name :");

        lblPropertyAddress.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        lblPropertyAddress.setText("Property Address :");

        lblCity.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        lblCity.setText("City :");

        lblState.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        lblState.setText("State :");

        lblPinCode.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        lblPinCode.setText("Pin Code :");

        btnBack.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPropertyName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPropertyNameValue, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPinCode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPincodeValue, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPropertyAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPropertyAddressValue, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblState)
                                .addGap(12, 12, 12))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCity)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStateValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCityValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(259, 259, 259))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblViewApprovedProperty, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblViewApprovedProperty, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPropertyNameValue, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPropertyName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPropertyAddressValue, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblPropertyAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCityValue, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCity))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStateValue, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblState))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPincodeValue, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPinCode))
                .addContainerGap(346, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        workArea.remove(this);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCityValue;
    private javax.swing.JLabel lblPinCode;
    private javax.swing.JLabel lblPincodeValue;
    private javax.swing.JLabel lblPropertyAddress;
    private javax.swing.JLabel lblPropertyAddressValue;
    private javax.swing.JLabel lblPropertyName;
    private javax.swing.JLabel lblPropertyNameValue;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblStateValue;
    private javax.swing.JLabel lblViewApprovedProperty;
    // End of variables declaration//GEN-END:variables
}
