/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Business.Applicant;
import Business.ApplicantDirectory;
import Business.Application;
import Business.InterestedCustomer;
import Business.InterestedCustomerDirectory;
import Business.Property;
import Business.PropertyDirectory;
import javax.swing.JPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ayush
 */
public class ApplicantViewApplicationsJPanel extends javax.swing.JPanel {
    private JPanel workArea;
    private ApplicantDirectory applicantDirectory;
    private Applicant applicant;
    private PropertyDirectory propertyDirectory;

    /**
     * Creates new form ApplicantViewPropertiesJPanel
     */
    public ApplicantViewApplicationsJPanel(JPanel workArea, ApplicantDirectory applicantDirectory, Applicant applicant, PropertyDirectory propertyDirectory) {
        initComponents();
        this.workArea = workArea;
        this.applicantDirectory = applicantDirectory;
        this.applicant = applicant;
        this.propertyDirectory = propertyDirectory;
        
        populateApplicationsTable();
        
//        for(Application application : applicant.getApplicationDirectory().getApplicationDirectory()){
//            System.out.println(application.getApplicationID());
//        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblViewApplicationsTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblViewApplications = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        lblPropertyName = new javax.swing.JLabel();
        lblPropertyNameValue = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblAddressValue = new javax.swing.JLabel();
        lblNumberOfRoomates = new javax.swing.JLabel();
        txtNumberOfRoomates = new javax.swing.JTextField();
        lblBudget = new javax.swing.JLabel();
        txtBudget = new javax.swing.JTextField();
        lblFeedback = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaFeedback = new javax.swing.JTextArea();
        btnUpdate = new javax.swing.JButton();
        lblPropertyId = new javax.swing.JLabel();
        lblPropertyIdValue = new javax.swing.JLabel();

        setBackground(new java.awt.Color(223, 223, 223));

        lblViewApplicationsTitle.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        lblViewApplicationsTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewApplicationsTitle.setText("View Applications");

        btnBack.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tblViewApplications.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        tblViewApplications.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Property Id", "Property Name", "Property Address", "Number of Roomates", "Budget", "Feedback"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblViewApplications);

        btnView.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        btnView.setText("View ");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        lblPropertyName.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        lblPropertyName.setText("Property Name :");

        lblPropertyNameValue.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        lblPropertyNameValue.setText("        ");

        lblAddress.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        lblAddress.setText("Address :");

        lblAddressValue.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        lblAddressValue.setText("    ");

        lblNumberOfRoomates.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        lblNumberOfRoomates.setText("Number of Roomates :");

        txtNumberOfRoomates.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        txtNumberOfRoomates.setText(" ");

        lblBudget.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        lblBudget.setText("Budget :");

        txtBudget.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N

        lblFeedback.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        lblFeedback.setText("Feedback :");

        txtAreaFeedback.setEditable(false);
        txtAreaFeedback.setColumns(20);
        txtAreaFeedback.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        txtAreaFeedback.setRows(5);
        jScrollPane2.setViewportView(txtAreaFeedback);

        btnUpdate.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        lblPropertyId.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        lblPropertyId.setText("Property Id :");

        lblPropertyIdValue.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        lblPropertyIdValue.setText("                      ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPropertyId)
                    .addComponent(lblFeedback)
                    .addComponent(lblBudget)
                    .addComponent(lblNumberOfRoomates)
                    .addComponent(lblAddress)
                    .addComponent(lblPropertyName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpdate)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblAddressValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNumberOfRoomates, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPropertyIdValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPropertyNameValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(295, 295, 295))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addGap(18, 18, 18)
                                .addComponent(lblViewApplicationsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblViewApplicationsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPropertyId)
                    .addComponent(lblPropertyIdValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPropertyNameValue)
                    .addComponent(lblPropertyName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress)
                    .addComponent(lblAddressValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumberOfRoomates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumberOfRoomates))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBudget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBudget)))
                    .addComponent(lblFeedback))
                .addGap(38, 38, 38)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        workArea.remove(this);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed

        // TODO add your handling code here:
                int selectedRow = tblViewApplications.getSelectedRow();
        
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null,"Please select a row from table first to view details", "Warning",JOptionPane.WARNING_MESSAGE);
        }
        else{
            DefaultTableModel model = (DefaultTableModel) tblViewApplications.getModel();
            
            String propertyId = (String) model.getValueAt(selectedRow, 0); 
            String propertyName = (String) model.getValueAt(selectedRow, 1);
            String Address = (String) model.getValueAt(selectedRow, 2);
            String feedback = (String) model.getValueAt(selectedRow, 5);
            String numberOfRoomates = (String) model.getValueAt(selectedRow, 3);
            String budget = (String) model.getValueAt(selectedRow, 4);

            lblPropertyIdValue.setText(propertyId);
            lblPropertyNameValue.setText(propertyName);
            lblAddressValue.setText(Address);
            txtAreaFeedback.setText(feedback);
            txtNumberOfRoomates.setText(numberOfRoomates);
            txtBudget.setText(budget);
        }
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String propertyId = lblPropertyIdValue.getText();
        Property property = propertyDirectory.searchPropertyById(propertyId);
        InterestedCustomerDirectory interestedCustomerDirectory = property.getInterestedCustomerDirectory();
        
        InterestedCustomer interestedCustomer = interestedCustomerDirectory.getInterestedCustomerById(applicant.getApplicantID());
        interestedCustomer.setNumberOfRoomates(txtNumberOfRoomates.getText());
        interestedCustomer.setDepositAmount(txtBudget.getText());
        JOptionPane.showMessageDialog(null,"Applicant Details Updated!");
        txtAreaFeedback.setText("");
        txtNumberOfRoomates.setText("");
        txtBudget.setText("");
        populateApplicationsTable();
    }//GEN-LAST:event_btnUpdateActionPerformed
        private void populateApplicationsTable(){
        DefaultTableModel dtm = (DefaultTableModel) tblViewApplications.getModel();
        dtm.setRowCount(0);
        
        
        for (Application application : applicant.getApplicationDirectory().getApplicationDirectory()){
            
            String applicationId = application.getApplicationID();

            Property property = propertyDirectory.searchPropertyById(applicationId);
            
                InterestedCustomerDirectory interestedCustomerDirectory = property.getInterestedCustomerDirectory();
                String feedback = interestedCustomerDirectory.getInterestedCustomerById(applicant.getApplicantID()).getFeedback();
                String numberOfRoomates = interestedCustomerDirectory.getInterestedCustomerById(applicant.getApplicantID()).getNumberOfRoomates(); 
                String budget = interestedCustomerDirectory.getInterestedCustomerById(applicant.getApplicantID()).getDepositAmount();
                
                if(property.isIsOwnerApproved() && !property.isIsTaken()){
                    Object[] row = new Object[6];
                    row[0] = applicationId;
                    row[1] = property.getName();
                    row[2] = property.getAddress();
                    row[3] = numberOfRoomates;
                    row[4] = budget;
                    row[5] = feedback;
                    dtm.addRow(row);                 
                }
                       
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAddressValue;
    private javax.swing.JLabel lblBudget;
    private javax.swing.JLabel lblFeedback;
    private javax.swing.JLabel lblNumberOfRoomates;
    private javax.swing.JLabel lblPropertyId;
    private javax.swing.JLabel lblPropertyIdValue;
    private javax.swing.JLabel lblPropertyName;
    private javax.swing.JLabel lblPropertyNameValue;
    private javax.swing.JLabel lblViewApplicationsTitle;
    private javax.swing.JTable tblViewApplications;
    private javax.swing.JTextArea txtAreaFeedback;
    private javax.swing.JTextField txtBudget;
    private javax.swing.JTextField txtNumberOfRoomates;
    // End of variables declaration//GEN-END:variables
}
