/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Business.AnnouncementDirectory;
import Business.Applicant;
import Business.ApplicantDirectory;
import Business.ApplicationDirectory;
import Business.Application;
import Business.ApplicationDirectory;
import Business.PropertyDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Ayush
 */
public class ApplicantJPanel extends javax.swing.JPanel {
    private JPanel workArea;
    private ApplicantDirectory applicantDirectory;
    private Applicant applicant;
    private PropertyDirectory propertyDirectory;
    private AnnouncementDirectory announcementDirectory;


    /**
     * Creates new form ApplicantJPanel
     */
    public ApplicantJPanel(JPanel workArea, ApplicantDirectory applicantDirectory, Applicant applicant, PropertyDirectory propertyDirectory, AnnouncementDirectory announcementDirectory) {
        initComponents();
        this.workArea = workArea;
        this.applicantDirectory = applicantDirectory;
        this.applicant = applicant;
        this.propertyDirectory = propertyDirectory;
        this.announcementDirectory = announcementDirectory;
        lblApplicantTitle.setText("Hello " + applicant.getApplicantName() + "!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblApplicantTitle = new javax.swing.JLabel();
        btnLogOutStudentArea = new javax.swing.JButton();
        btnApplyForProperties = new javax.swing.JButton();
        btnViewApplications = new javax.swing.JButton();
        btnViewApprovedProperties = new javax.swing.JButton();
        btnViewAnnouncements = new javax.swing.JButton();

        setBackground(new java.awt.Color(223, 223, 223));

        lblApplicantTitle.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        lblApplicantTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblApplicantTitle.setText("Hello Applicant");

        btnLogOutStudentArea.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        btnLogOutStudentArea.setText("<< Log Out");
        btnLogOutStudentArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutStudentAreaActionPerformed(evt);
            }
        });

        btnApplyForProperties.setBackground(new java.awt.Color(0, 0, 0));
        btnApplyForProperties.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        btnApplyForProperties.setForeground(new java.awt.Color(255, 255, 255));
        btnApplyForProperties.setText("Apply for Properties");
        btnApplyForProperties.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyForPropertiesActionPerformed(evt);
            }
        });

        btnViewApplications.setBackground(new java.awt.Color(0, 0, 0));
        btnViewApplications.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        btnViewApplications.setForeground(new java.awt.Color(255, 255, 255));
        btnViewApplications.setText("View Applications");
        btnViewApplications.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewApplicationsActionPerformed(evt);
            }
        });

        btnViewApprovedProperties.setBackground(new java.awt.Color(0, 0, 0));
        btnViewApprovedProperties.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        btnViewApprovedProperties.setForeground(new java.awt.Color(255, 255, 255));
        btnViewApprovedProperties.setText("View Approved Properties");
        btnViewApprovedProperties.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewApprovedPropertiesActionPerformed(evt);
            }
        });

        btnViewAnnouncements.setBackground(new java.awt.Color(0, 0, 0));
        btnViewAnnouncements.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        btnViewAnnouncements.setForeground(new java.awt.Color(255, 255, 255));
        btnViewAnnouncements.setText("View Announcements");
        btnViewAnnouncements.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAnnouncementsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblApplicantTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnViewApprovedProperties)
                            .addComponent(btnApplyForProperties, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnViewApplications, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnViewAnnouncements)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnLogOutStudentArea, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblApplicantTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApplyForProperties, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewApplications, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewApprovedProperties, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewAnnouncements, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 240, Short.MAX_VALUE)
                .addComponent(btnLogOutStudentArea, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutStudentAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutStudentAreaActionPerformed
        // TODO add your handling code here:
        workArea.remove(this);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_btnLogOutStudentAreaActionPerformed

    private void btnApplyForPropertiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyForPropertiesActionPerformed

            Boolean isApplicationApproved = false;
            
            if(propertyDirectory.isPropertyRentedTo(applicant.getApplicantID())){
                isApplicationApproved = true;
            }
        
        if(isApplicationApproved){
            JOptionPane.showMessageDialog(null,"Your application is approved. Check Approved Property Section!");
        }else{
        ApplicantApplyPropertiesJPanel applicantApplyPropertiesJPanel = new ApplicantApplyPropertiesJPanel(workArea, applicantDirectory, applicant, propertyDirectory);
        workArea.add("ApplicantApplyPropertiesJPanel", applicantApplyPropertiesJPanel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
        }
    }//GEN-LAST:event_btnApplyForPropertiesActionPerformed

    private void btnViewApplicationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewApplicationsActionPerformed
        // TODO add your handling code here:       
            
            Boolean isApplicationApproved = false;
            
            if(propertyDirectory.isPropertyRentedTo(applicant.getApplicantID())){
                isApplicationApproved = true;
            }
            
        
        if(isApplicationApproved){
            JOptionPane.showMessageDialog(null,"Your application is approved. Check Approved Property Section!");
        }else{
        ApplicantViewApplicationsJPanel applicantViewApplicationsJPanel = new ApplicantViewApplicationsJPanel(workArea, applicantDirectory, applicant, propertyDirectory);
        workArea.add("ApplicantViewApplicationsJPanel", applicantViewApplicationsJPanel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);      
        }
           

    }//GEN-LAST:event_btnViewApplicationsActionPerformed

    private void btnViewApprovedPropertiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewApprovedPropertiesActionPerformed
        // TODO add your handling code here:

        Boolean isApplicationApproved = false;
            
        if(propertyDirectory.isPropertyRentedTo(applicant.getApplicantID())){
            isApplicationApproved = true;
        }
        
        
        if(!isApplicationApproved){
            JOptionPane.showMessageDialog(null,"Your application is not approved yet!");
        }else{
         ApplicantViewApprovedPropertiesJPanel applicantViewApprovedPropertiesJPanel = new ApplicantViewApprovedPropertiesJPanel(workArea, applicantDirectory, applicant, propertyDirectory);
        workArea.add("ApplicantViewApprovedPropertiesJPanel", applicantViewApprovedPropertiesJPanel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
        }
        

    }//GEN-LAST:event_btnViewApprovedPropertiesActionPerformed

    private void btnViewAnnouncementsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAnnouncementsActionPerformed
//        ApplicantViewAnnouncementJPanel
                
        ApplicantViewAnnouncementJPanel applicantViewApprovedPropertiesJPanel = new ApplicantViewAnnouncementJPanel(workArea, announcementDirectory);
        workArea.add("ApplicantViewAnnouncementJPanel", applicantViewApprovedPropertiesJPanel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnViewAnnouncementsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApplyForProperties;
    private javax.swing.JButton btnLogOutStudentArea;
    private javax.swing.JButton btnViewAnnouncements;
    private javax.swing.JButton btnViewApplications;
    private javax.swing.JButton btnViewApprovedProperties;
    private javax.swing.JLabel lblApplicantTitle;
    // End of variables declaration//GEN-END:variables
}
