/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Business.Student;
import Business.StudentDirectory;
import javax.swing.JPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Ayush
 */
public class CertificateAuthorityJPanel extends javax.swing.JPanel {
    
        private StudentDirectory studentDirectory;
        private JPanel workArea;
          




    /**
     * Creates new form CertificateAuthorityJPanel
     */
    public CertificateAuthorityJPanel(JPanel workArea  ,StudentDirectory studentDirectory) {
        initComponents();
        this.workArea = workArea;
        this.studentDirectory = studentDirectory;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupDegreeGranted = new javax.swing.ButtonGroup();
        lblCertificateAuthorityTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRqstStudents = new javax.swing.JTable();
        btnLogOut = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        txtStudentName = new javax.swing.JTextField();
        txtStudentUsername = new javax.swing.JTextField();
        lblStudentName = new javax.swing.JLabel();
        lblStudentUsername = new javax.swing.JLabel();
        rdBtnYes = new javax.swing.JRadioButton();
        rdBtnNo = new javax.swing.JRadioButton();
        lblDegreeGranted = new javax.swing.JLabel();
        txtEmailId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();

        lblCertificateAuthorityTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCertificateAuthorityTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCertificateAuthorityTitle.setText("Hello Certificate Authority");

        tblRqstStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Student Name", "Student Username", "Email Id", "Is Requested", "Student Id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRqstStudents);

        btnLogOut.setText("<<Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        lblStudentName.setText("Student Name :");

        lblStudentUsername.setText("Student Username :");

        btnGroupDegreeGranted.add(rdBtnYes);
        rdBtnYes.setText("Yes");

        btnGroupDegreeGranted.add(rdBtnNo);
        rdBtnNo.setText("No");

        lblDegreeGranted.setText("Degree Granted :");

        jLabel1.setText("Student Email Id :");

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCertificateAuthorityTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnView)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(106, 106, 106))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnLogOut))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblStudentName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblStudentUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDegreeGranted, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(rdBtnNo)
                        .addComponent(rdBtnYes)
                        .addComponent(txtStudentName)
                        .addComponent(txtStudentUsername)
                        .addComponent(txtEmailId, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                    .addComponent(btnUpdate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblCertificateAuthorityTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnView)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStudentName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStudentUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStudentUsername))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogOut)
                        .addGap(74, 74, 74))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDegreeGranted)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdBtnYes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdBtnNo)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate)
                        .addContainerGap(83, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        workArea.remove(this);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = tblRqstStudents.getSelectedRow();
        
       if(selectedRow < 0){
                JOptionPane.showMessageDialog(null,"Please select a row from table first to view details", "Warning",JOptionPane.WARNING_MESSAGE);
            } else {
                DefaultTableModel model = (DefaultTableModel) tblRqstStudents.getModel();
//                Professor professor = (Professor) model.getValueAt(selectedRow, 2);
                
            String studentName = (String) model.getValueAt(selectedRow, 0);
            String studentUsername = (String) model.getValueAt(selectedRow, 1);
            String emailId = (String) model.getValueAt(selectedRow, 2);
            boolean certificateRequested = (boolean) model.getValueAt(selectedRow,3);

            txtStudentName.setText(studentName);
            txtStudentUsername.setText(studentUsername);
            txtEmailId.setText(emailId);
            
            if(certificateRequested){
                rdBtnNo.setSelected(true);
                }
            else{
                rdBtnYes.setSelected(true);
                }
            

            }
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        if("".equals(txtStudentName.getText())) {
            JOptionPane.showMessageDialog(null,"Please enter the Student Name");
        } else if ("".equals(txtStudentUsername.getText())) {
            JOptionPane.showMessageDialog(null,"Please enter the Student Username");
        } else if ("".equals(txtEmailId.getText())){
            JOptionPane.showMessageDialog(null, "Please enter the Student Email Id");
        }
        else {
            int selectedRow = tblRqstStudents.getSelectedRow();

            DefaultTableModel model = (DefaultTableModel) tblRqstStudents.getModel();

            String studentId = (String) model.getValueAt(selectedRow, 4);
            
            Student student = studentDirectory.searchStudentByStudentId(studentId);
            student.setStudentName(txtStudentName.getText());
            student.setStudentUserName(txtStudentUsername.getText());
            student.setStudentEmailID(txtEmailId.getText());
            
            if(rdBtnYes.isSelected()){
                student.setDegreegranted(true);
            }
            else{
                student.setDegreegranted(false);
            }

            JOptionPane.showMessageDialog(null,"Student Details Updated Successfully!");
            
            txtStudentName.setText("");
            txtStudentUsername.setText("");
            txtEmailId.setText("");
            rdBtnNo.setSelected(true);
            populateTable();
        }
        
        
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupDegreeGranted;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCertificateAuthorityTitle;
    private javax.swing.JLabel lblDegreeGranted;
    private javax.swing.JLabel lblStudentName;
    private javax.swing.JLabel lblStudentUsername;
    private javax.swing.JRadioButton rdBtnNo;
    private javax.swing.JRadioButton rdBtnYes;
    private javax.swing.JTable tblRqstStudents;
    private javax.swing.JTextField txtEmailId;
    private javax.swing.JTextField txtStudentName;
    private javax.swing.JTextField txtStudentUsername;
    // End of variables declaration//GEN-END:variables

    private void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel) tblRqstStudents.getModel();
        dtm.setRowCount(0);
        for (Student student : studentDirectory.getStudentDirectory()){
           if(student.isCertificateRequested() && !student.isDegreegranted()){
            Object[] row = new Object[5];
            row[0] = student.getStudentName();
            row[1] = student.getStudentUserName();
            row[2] = student.getStudentEmailID();
            row[3] = student.isCertificateRequested();
            row[4] = student.getStudentID();
            dtm.addRow(row);
           }             
        }
    }
    
}
