/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Business.University;
import Business.UniversityDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sawan
 */
public class ContactCampusConnectJPanel extends javax.swing.JPanel {

        private JPanel workArea;
    private University university;
    private UniversityDirectory universityDirectory;
    /**
     * Creates new form ContactCampusConnectJPanel
     */
    public ContactCampusConnectJPanel(JPanel workArea,University university, UniversityDirectory universityDirectory) {
        initComponents();
                this.workArea = workArea;
        this.universityDirectory = universityDirectory;
        this.university = university;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblContactCampusConnectTitle = new javax.swing.JLabel();
        lblOffCampusStudents = new javax.swing.JLabel();
        txtOffCampusStudents = new javax.swing.JTextField();
        lblIncomingStudents = new javax.swing.JLabel();
        txtIncomingStudents = new javax.swing.JTextField();
        btnSendData = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblGraduatedStudents = new javax.swing.JLabel();
        txtGraduatedStudents = new javax.swing.JTextField();
        lblOnCampusStudents = new javax.swing.JLabel();
        txtOnCampusStudents = new javax.swing.JTextField();

        setBackground(new java.awt.Color(223, 223, 223));

        lblContactCampusConnectTitle.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        lblContactCampusConnectTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContactCampusConnectTitle.setText("Share Insights");

        lblOffCampusStudents.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        lblOffCampusStudents.setText("Off Campus Living Students:");

        txtOffCampusStudents.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        txtOffCampusStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOffCampusStudentsActionPerformed(evt);
            }
        });

        lblIncomingStudents.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        lblIncomingStudents.setText("Incoming students in next intake:");

        txtIncomingStudents.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N

        btnSendData.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        btnSendData.setText("Send");
        btnSendData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendDataActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblGraduatedStudents.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        lblGraduatedStudents.setText("Students graduating this year:");

        txtGraduatedStudents.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        txtGraduatedStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGraduatedStudentsActionPerformed(evt);
            }
        });

        lblOnCampusStudents.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        lblOnCampusStudents.setText("On Campus Living Students:");

        txtOnCampusStudents.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        txtOnCampusStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOnCampusStudentsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblContactCampusConnectTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(lblGraduatedStudents)
                .addGap(26, 26, 26)
                .addComponent(txtGraduatedStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOffCampusStudents, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblOnCampusStudents, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblIncomingStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSendData, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIncomingStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOnCampusStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOffCampusStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(188, 188, 188))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblContactCampusConnectTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGraduatedStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGraduatedStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIncomingStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIncomingStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOnCampusStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOnCampusStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblOffCampusStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(txtOffCampusStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnSendData, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(207, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtOffCampusStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOffCampusStudentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOffCampusStudentsActionPerformed

    private void btnSendDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendDataActionPerformed
        // TODO add your handling code here:
//        String graduatedStudents = university.getGraduatedStudents();
//        String incomingStudents = university.getIncomingStudents();
//        String offCampusStudent = university.getOffCampusStudents();
//        String onCampusStudent = university.getOnCampusStudents();
// 
        
       university.setGraduatedStudents(txtGraduatedStudents.getText());
        university.setIncomingStudents(txtIncomingStudents.getText());
        university.setOnCampusStudents(txtOnCampusStudents.getText());
        university.setOffCampusStudents(txtOffCampusStudents.getText());
        System.out.println("graduated students" + txtGraduatedStudents.getText());
        System.out.println("incoming students" + txtIncomingStudents.getText());
        System.out.println("on campus students" + txtOnCampusStudents.getText());
        System.out.println("off campus students" + txtOffCampusStudents.getText());
        JOptionPane.showMessageDialog(null, "Submitted!");
        
    }//GEN-LAST:event_btnSendDataActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workArea.remove(this);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtGraduatedStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGraduatedStudentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGraduatedStudentsActionPerformed

    private void txtOnCampusStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOnCampusStudentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOnCampusStudentsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSendData;
    private javax.swing.JLabel lblContactCampusConnectTitle;
    private javax.swing.JLabel lblGraduatedStudents;
    private javax.swing.JLabel lblIncomingStudents;
    private javax.swing.JLabel lblOffCampusStudents;
    private javax.swing.JLabel lblOnCampusStudents;
    private javax.swing.JTextField txtGraduatedStudents;
    private javax.swing.JTextField txtIncomingStudents;
    private javax.swing.JTextField txtOffCampusStudents;
    private javax.swing.JTextField txtOnCampusStudents;
    // End of variables declaration//GEN-END:variables
}
