/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Business.Hashing;
import java.util.UUID;
import javax.swing.JOptionPane;
import Business.CertificateAuthority;
import Business.CertificateAuthorityDirectory;
import javax.swing.JPanel;
import java.awt.CardLayout;
/**
 *
 * @author Ayush
 */
public class CreateCertificateAuthorityJPanel extends javax.swing.JPanel {
    private JPanel workArea;
    private CertificateAuthorityDirectory certificateAuthorityDirectory;

    /**
     * Creates new form CreateCertificateAuthorityJPanel
     */
    public CreateCertificateAuthorityJPanel(JPanel workArea, CertificateAuthorityDirectory certificateAuthorityDirectory) {
        initComponents();
        this.workArea = workArea;
        this.certificateAuthorityDirectory = certificateAuthorityDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCreateCertificateAuthority = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        txtContact = new javax.swing.JTextField();
        txtEmailID = new javax.swing.JTextField();
        lblEmailID = new javax.swing.JLabel();
        lblContact = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblFullName = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        btnBAck = new javax.swing.JButton();

        lblCreateCertificateAuthority.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCreateCertificateAuthority.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreateCertificateAuthority.setText("Create Certificate Authority");

        txtFullName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtUserName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtContact.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactActionPerformed(evt);
            }
        });

        txtEmailID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEmailID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailIDActionPerformed(evt);
            }
        });

        lblEmailID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEmailID.setText("Email ID:");

        lblContact.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblContact.setText("Contact:");

        lblPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPassword.setText("Password:");

        lblUserName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUserName.setText("Username:");

        lblFullName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFullName.setText("Full Name:");

        btnCreate.setBackground(new java.awt.Color(102, 153, 255));
        btnCreate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCreate.setText("Create");
        btnCreate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnBAck.setText("<<Back");
        btnBAck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBAckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(219, 219, 219)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUserName, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblContact, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblEmailID, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnBAck)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblFullName)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFullName)
                            .addComponent(txtUserName)
                            .addComponent(txtContact)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmailID)
                            .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblCreateCertificateAuthority, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCreateCertificateAuthority, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblFullName)
                        .addComponent(btnBAck))
                    .addComponent(txtFullName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserName)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContact)
                    .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmailID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(301, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactActionPerformed

    private void txtEmailIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailIDActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // Handle professor, student and employer sign up:
        String fullName = txtFullName.getText();
        String userName = txtUserName.getText();
        String password = txtPassword.getText();
        String contact = txtContact.getText();
        String emailID = txtEmailID.getText();
        String hashedPassword = Hashing.encrypt(password, "secretKey");
        
        if(fullName.equals("")) {
            JOptionPane.showMessageDialog(null,"Full Name cannot be empty", "Warning",JOptionPane.WARNING_MESSAGE);
        } else if(fullName.length() <= 2) {
            JOptionPane.showMessageDialog(null,"Full Name should have more than 2 characters", "Warning",JOptionPane.WARNING_MESSAGE);
        } else if(userName.equals("")) {
            JOptionPane.showMessageDialog(null,"Username cannot be empty", "Warning",JOptionPane.WARNING_MESSAGE);
        } else if(userName.length() <= 3) {
            JOptionPane.showMessageDialog(null,"Username should have more than 3 characters", "Warning",JOptionPane.WARNING_MESSAGE);
        } else if(password.equals("")) {
            JOptionPane.showMessageDialog(null,"Password cannot be empty", "Warning",JOptionPane.WARNING_MESSAGE);
        } else if(contact.equals("")) {
            JOptionPane.showMessageDialog(null,"Contact cannot be empty", "Warning",JOptionPane.WARNING_MESSAGE);
        } else if(contact.matches(".*[^0-9].*") || contact.length() != 10 ) {
            JOptionPane.showMessageDialog(null,"Invalid contact", "Warning",JOptionPane.WARNING_MESSAGE);
        } else if(emailID.equals("")) {
            JOptionPane.showMessageDialog(null,"Email ID cannot be empty", "Warning",JOptionPane.WARNING_MESSAGE);
        }
        else{
            UUID certificateAuthorityID =  null;
            certificateAuthorityID = UUID.randomUUID();

            CertificateAuthority certificateAuthority = certificateAuthorityDirectory.addCertificateAuthority();
            certificateAuthority.setCertificateAuthorityID("Professor-"+certificateAuthorityID.toString());
            certificateAuthority.setCertificateAuthorityName(fullName);
            certificateAuthority.setCertificateAuthorityUserName(userName);
            certificateAuthority.setCertificateAuthorityPassword(hashedPassword);
            certificateAuthority.setCertificateAuthorityPhoneNumber(contact);
            certificateAuthority.setCertificateAuthorityID(emailID);

            JOptionPane.showMessageDialog(null,"Certificate Authority Registered Successfully!");

            txtFullName.setText("");
            txtUserName.setText("");
            txtPassword.setText("");
            txtContact.setText("");
            txtEmailID.setText("");
        }


    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnBAckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBAckActionPerformed
        workArea.remove(this);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_btnBAckActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBAck;
    private javax.swing.JButton btnCreate;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblCreateCertificateAuthority;
    private javax.swing.JLabel lblEmailID;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtEmailID;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
