/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Business.Student;
import javax.swing.JPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
/**
 *
 * @author Ayush
 */
public class FinancialAidRequestJPanel extends javax.swing.JPanel {
        private JPanel workArea;
    private Student student;
    /**
     * Creates new form FinancialAidRequestJPanel
     */
    public FinancialAidRequestJPanel(JPanel workArea  ,Student student) {
        initComponents();
        this.workArea = workArea;
        this.student = student;
        lblStudentNameValue.setText(student.getStudentName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRequestFinancialAid = new javax.swing.JLabel();
        lblStudentName = new javax.swing.JLabel();
        lblStudentNameValue = new javax.swing.JLabel();
        lblFinancialAidReason = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaFinancialAidReason = new javax.swing.JTextArea();
        btnSubmit = new javax.swing.JButton();
        btnShowStatus = new javax.swing.JButton();
        btnBackRequestForFinancialAid = new javax.swing.JButton();
        lblFinancialAidStatus = new javax.swing.JLabel();

        lblRequestFinancialAid.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblRequestFinancialAid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRequestFinancialAid.setText("Request For Financial Aid");

        lblStudentName.setText("Name :");

        lblFinancialAidReason.setText("Financial Aid Reason :");

        txtAreaFinancialAidReason.setColumns(20);
        txtAreaFinancialAidReason.setRows(5);
        jScrollPane1.setViewportView(txtAreaFinancialAidReason);

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnShowStatus.setText("Check Status");
        btnShowStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowStatusActionPerformed(evt);
            }
        });

        btnBackRequestForFinancialAid.setText("<<Back");
        btnBackRequestForFinancialAid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackRequestForFinancialAidActionPerformed(evt);
            }
        });

        lblFinancialAidStatus.setText("                                                                                                                             ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblRequestFinancialAid, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(207, 207, 207)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblFinancialAidReason)
                                    .addComponent(lblStudentName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSubmit)
                                    .addComponent(lblStudentNameValue, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBackRequestForFinancialAid)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnShowStatus)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblFinancialAidStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRequestFinancialAid, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStudentName)
                            .addComponent(lblStudentNameValue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFinancialAidReason)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSubmit)
                        .addGap(38, 38, 38)
                        .addComponent(btnShowStatus))
                    .addComponent(lblFinancialAidStatus))
                .addGap(18, 18, 18)
                .addComponent(btnBackRequestForFinancialAid)
                .addGap(0, 294, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        if("".equals(txtAreaFinancialAidReason.getText())){
            JOptionPane.showMessageDialog(null,"Please enter the reason");
        }else if(student.isFinancialAidGranted() || student.isFinancialAidRequested()){
                    JOptionPane.showMessageDialog(null,"Cannot place request as a request has already being placed.");
        }
        else{
        student.setFinancialAidReason(txtAreaFinancialAidReason.getText());  
        student.setFinancialAidRequested(true);
        JOptionPane.showMessageDialog(null,"Request Sent");
        txtAreaFinancialAidReason.setText("");
        }   
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnShowStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowStatusActionPerformed
        // TODO add your handling code here:
        if(student.isFinancialAidGranted()){
            lblFinancialAidStatus.setText("Financial Aid has been granted to you.");
        }
        else if(student.isFinancialAidRequested() && !student.isFinancialAidGranted()){
            lblFinancialAidStatus.setText("Your financial aid request is in review.");
        }
        else{
            lblFinancialAidStatus.setText("You have not requested financial aid.");
        }
    }//GEN-LAST:event_btnShowStatusActionPerformed

    private void btnBackRequestForFinancialAidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackRequestForFinancialAidActionPerformed
        // TODO add your handling code here:
        workArea.remove(this);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_btnBackRequestForFinancialAidActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackRequestForFinancialAid;
    private javax.swing.JButton btnShowStatus;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFinancialAidReason;
    private javax.swing.JLabel lblFinancialAidStatus;
    private javax.swing.JLabel lblRequestFinancialAid;
    private javax.swing.JLabel lblStudentName;
    private javax.swing.JLabel lblStudentNameValue;
    private javax.swing.JTextArea txtAreaFinancialAidReason;
    // End of variables declaration//GEN-END:variables
}
