/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Business.Owner;
import Business.Property;
import Business.PropertyDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class OwnerViewJPanel extends javax.swing.JPanel {
    private JPanel workArea;
    private Owner owner;
    private PropertyDirectory propertyDirectory;
    /**
     * Creates new form OwnerViewJPanel
     */
    public OwnerViewJPanel(JPanel workArea, Owner owner, PropertyDirectory propertyDirectory) {
        initComponents();
         this.workArea = workArea;
        this.propertyDirectory = propertyDirectory;
        this.owner = owner;
        populatePropertyTable();
    }
    
    public void populatePropertyTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblProperties.getModel();
        dtm.setRowCount(0);
        for(Property property: propertyDirectory.getPropertyDirectory()){
            if(owner.getOwnerName() != null && owner.getOwnerName().equals(property.getOwner().getOwnerName())) {
                Object[] row = new Object[6];
            row[0] = property.getName();
            row[1] = property.getAddress();
            row[2] = property.getPincode();
            row[3] = property.getBroker().getBrokerName();
            row[4] = property.getBroker().getBrokerPhoneNumber();
            if(property.isIsTaken() == true) {
                row[5] = "Yes";
            } else {
                row[5] = "No";
            }
//            row[5] = "Yes" ? property.isIsTaken() : "No"; 
            
            dtm.addRow(row);
        }
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAvailablePropertiesList = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProperties = new javax.swing.JTable();

        setBackground(new java.awt.Color(223, 223, 223));

        lblAvailablePropertiesList.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        lblAvailablePropertiesList.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAvailablePropertiesList.setText("View Your Listed Properties");

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tblProperties.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        tblProperties.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Address", "Pincode", "Broker Name", "Broker Phone ", "Leased"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProperties);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(lblAvailablePropertiesList, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAvailablePropertiesList, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        workArea.remove(this);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAvailablePropertiesList;
    private javax.swing.JTable tblProperties;
    // End of variables declaration//GEN-END:variables
}
