/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Business.Broker;
import Business.BrokerDirectory;
import Business.Course;
import Business.Employer;
import Business.InterestedCustomerDirectory;
import Business.Management;
import Business.ManagementDirectory;
import Business.Owner;
import Business.Property;
import Business.PropertyDirectory;
import Business.University;
import Business.UniversityDirectory;
import java.awt.CardLayout;
import java.util.UUID;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author admin
 */
public class OwnerAddPropJPanel extends javax.swing.JPanel {
    private JPanel workArea;
    private PropertyDirectory propertyDirectory;
    private Owner owner;
    private BrokerDirectory brokerDirectory;
 private ManagementDirectory managementDIrectory;
 private UniversityDirectory universityDirectory;
    
    /**
     * Creates new form OwnerAddPropJPanel
     */
    public OwnerAddPropJPanel(JPanel workArea, PropertyDirectory propertyDirectory, Owner owner, BrokerDirectory brokerDirectory, ManagementDirectory managementDIrectory, UniversityDirectory universityDirectory) {
        initComponents();
        this.workArea = workArea;
        this.propertyDirectory = propertyDirectory;
        this.owner = owner;
        this.managementDIrectory = managementDIrectory;
        this.brokerDirectory = brokerDirectory;
        this.universityDirectory = universityDirectory;
        fillManagementData();
        fillBrokerData();
        fillUniversityData();
    }
    
    public void fillManagementData() {
        for(Management mng : managementDIrectory.getManagementDirectory()) {
            mandropdown.addItem(mng.getManagementName());
        }
    }
    public void fillBrokerData() {
        for(Broker broker : brokerDirectory.getBrokerDirectory()) {
            brokerdropdown.addItem(broker.getBrokerName());
        }
    }
    
    public void fillUniversityData() {
        for(University university : universityDirectory.getUniversityDirectory()) {
            unidropdown.addItem(university.getUniversityName());
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAvailablePropertiesList = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaddress = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        txtpincode = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        unidropdown = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        mandropdown = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtintake = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        brokerdropdown = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtyoutube = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtCarpetArea = new javax.swing.JTextField();
        lblCarpetArea = new javax.swing.JLabel();

        setBackground(new java.awt.Color(223, 223, 223));

        lblAvailablePropertiesList.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        lblAvailablePropertiesList.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAvailablePropertiesList.setText("Add Properties");

        btnBack.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        jLabel1.setText("Property Name:");

        txtname.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        jLabel2.setText("Property Address:");

        txtaddress.setColumns(20);
        txtaddress.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        txtaddress.setRows(5);
        jScrollPane1.setViewportView(txtaddress);

        jLabel3.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        jLabel3.setText("Pincode:");

        txtpincode.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        jLabel4.setText("University:");

        unidropdown.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        jLabel5.setText("Management:");

        mandropdown.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        jLabel6.setText("Intake:");

        txtintake.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        jLabel7.setText("Broker:");

        brokerdropdown.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        jLabel8.setText("Youtube Link:");

        txtyoutube.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N

        jButton1.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        jButton1.setText("Add Property");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtCarpetArea.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        txtCarpetArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarpetAreaActionPerformed(evt);
            }
        });

        lblCarpetArea.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        lblCarpetArea.setText("Carpet Area :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAvailablePropertiesList, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(228, 228, 228)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(lblCarpetArea)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7)))
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtpincode, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtCarpetArea, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtyoutube, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                        .addComponent(brokerdropdown, javax.swing.GroupLayout.Alignment.LEADING, 0, 155, Short.MAX_VALUE)
                        .addComponent(txtintake, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                        .addComponent(mandropdown, javax.swing.GroupLayout.Alignment.LEADING, 0, 155, Short.MAX_VALUE)
                        .addComponent(unidropdown, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtname))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAvailablePropertiesList, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtpincode, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addComponent(jLabel3))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unidropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mandropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtintake, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brokerdropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtyoutube, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCarpetArea, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCarpetArea))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        workArea.remove(this);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_btnBackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Adding validation here
        
        
        UUID propertyID = null;
        propertyID = UUID.randomUUID();
        String propertyName = txtname.getText();
        String propertyAddress = txtaddress.getText();
        String city = "Boston";
        String state = "MA";
        String pincode = txtpincode.getText();
        String management = mandropdown.getSelectedItem().toString();
        String university = unidropdown.getSelectedItem().toString();
        String broker = brokerdropdown.getSelectedItem().toString();
        String intake = txtintake.getText();
        String youtubeLink = txtyoutube.getText();
        String carpetArea = txtCarpetArea.getText();
        
        Management selectedManagement = new Management();
        for(Management mng : managementDIrectory.getManagementDirectory()) {
            if(mng.getManagementName().equals(management)) {
                selectedManagement = mng;
            }
        }
        
        Broker selectedBroker = new Broker();
        for(Broker bro : brokerDirectory.getBrokerDirectory()) {
            if(bro.getBrokerName().equals(broker)) {
                selectedBroker = bro;
            }
        }
        
        University selectedUniversity = new University();
        for(University uni : universityDirectory.getUniversityDirectory()) {
            if(uni.getUniversityName().equals(university)) {
                selectedUniversity = uni;
            }
        }
        
        if(propertyName.equals("")) {
            JOptionPane.showMessageDialog(null,"Property Name cannot be empty", "Warning",JOptionPane.WARNING_MESSAGE);
        } else if(propertyAddress.equals("")) {
            JOptionPane.showMessageDialog(null,"Property Address cannot be empty", "Warning",JOptionPane.WARNING_MESSAGE);
        } else if(pincode.equals("")) {
            JOptionPane.showMessageDialog(null,"Property Pincode cannot be empty", "Warning",JOptionPane.WARNING_MESSAGE);
        } else if (intake.equals("")) {
            JOptionPane.showMessageDialog(null,"Intake cannot be empty", "Warning",JOptionPane.WARNING_MESSAGE);
        } else if (youtubeLink.equals(""))  {
            JOptionPane.showMessageDialog(null,"Youtube Link cannot be empty", "Warning",JOptionPane.WARNING_MESSAGE);
        } else if (carpetArea.equals(""))  {
            JOptionPane.showMessageDialog(null,"Carpet Area cannot be empty", "Warning",JOptionPane.WARNING_MESSAGE);
        } 
        else {
            Property property = propertyDirectory.addProperty();
        property.setPropertyId("Property-" + propertyID);
        property.setName(propertyName);
        property.setAddress(propertyAddress);
        property.setCity("Boston");
        property.setState("Massachusetts");
        property.setPincode(pincode);
        property.setManagement(selectedManagement);
        property.setUniversity(selectedUniversity);
        property.setBroker(selectedBroker);
        property.setIntake(intake);
        property.setRentedTo("");
        property.setIsTaken(false);
        property.setYoutubeLink(youtubeLink);
        property.setCartpetArea(carpetArea);
        property.setIsOwnerApproved(false);
        property.setOwner(owner);
        InterestedCustomerDirectory icd = new InterestedCustomerDirectory();
        property.setInterestedCustomerDirectory(icd);
        
        
        JOptionPane.showMessageDialog(null,"Property Added Successfully!");
        
        txtname.setText("");
        txtaddress.setText("");
        txtpincode.setText("");
        unidropdown.setSelectedItem("Northeastern University");
        mandropdown.setSelectedItem("Groma");
        brokerdropdown.setSelectedItem("Andrew Miller");
        txtintake.setText("");
        txtyoutube.setText("");
        txtCarpetArea.setText("");
        }
        
//        txtLanguage.setText("");
//        radioFall.setSelected(false);
//        radioSpring.setSelected(false);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtCarpetAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarpetAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarpetAreaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> brokerdropdown;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAvailablePropertiesList;
    private javax.swing.JLabel lblCarpetArea;
    private javax.swing.JComboBox<String> mandropdown;
    private javax.swing.JTextField txtCarpetArea;
    private javax.swing.JTextArea txtaddress;
    private javax.swing.JTextField txtintake;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtpincode;
    private javax.swing.JTextField txtyoutube;
    private javax.swing.JComboBox<String> unidropdown;
    // End of variables declaration//GEN-END:variables
}
