/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Business.Course;
import Business.CoursesDirectory;
import Business.DaySchedule;
import Business.Professor;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class ProfessorYourScheduleJPanel extends javax.swing.JPanel {
    private JPanel workArea;
    private CoursesDirectory coursesDirectory;
    private Professor professor;

    /**
     * Creates new form ProfessorYourScheduleJPanel
     */
    ProfessorYourScheduleJPanel(JPanel workArea, Professor professor, CoursesDirectory coursesDirectroy) {
        initComponents();
        this.workArea = workArea;
        this.professor = professor;
        this.coursesDirectory = coursesDirectroy;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblYourSchedule = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblViewSchedule = new javax.swing.JTable();

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblYourSchedule.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblYourSchedule.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblYourSchedule.setText("Your Schedule");

        tblViewSchedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Course Name", "Region", "Day", "Start Time", "End Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblViewSchedule);
        if (tblViewSchedule.getColumnModel().getColumnCount() > 0) {
            tblViewSchedule.getColumnModel().getColumn(0).setResizable(false);
            tblViewSchedule.getColumnModel().getColumn(1).setResizable(false);
            tblViewSchedule.getColumnModel().getColumn(2).setResizable(false);
            tblViewSchedule.getColumnModel().getColumn(3).setResizable(false);
            tblViewSchedule.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblYourSchedule, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblYourSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        workArea.remove(this);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblYourSchedule;
    private javax.swing.JTable tblViewSchedule;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblViewSchedule.getModel();
        dtm.setRowCount(0);
        for(Course course : coursesDirectory.getCourseDirectory()) {
            if(course.getProfessor().getProfessorName().equals(professor.getProfessorName())) {
                for(DaySchedule daySchedule : course.getSchedule().getDaySchedules()) {
                    Object[] row = new Object[5];
                    row[0] = course.getCourseName();
                    row[1] = course.getRegion();
                    row[2] = daySchedule.getDay();
                    row[3] = daySchedule.getStartTime();
                    row[4] = daySchedule.getEndTime();
            
                    dtm.addRow(row);
                }
            }
        }
    }
}
