/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Business.Course;
import Business.CoursesDirectory;
import Business.DaySchedule;
import Business.Professor;
import Business.Schedule;
import java.awt.CardLayout;
import java.util.UUID;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author admin
 */
public class ProfessorAddCourseJPanel extends javax.swing.JPanel {
    private JPanel workArea;
    private Professor professor;
    private CoursesDirectory coursesDirectory;
    Schedule schedule = new Schedule();

    /**
     * Creates new form ProfessorAddCourseJPanel
     */
    ProfessorAddCourseJPanel(JPanel workArea, CoursesDirectory coursesDirectory, Professor professor) {
        initComponents();
        this.workArea = workArea;
        this.professor = professor;
        this.coursesDirectory = coursesDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblAddCourse = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblCourseName = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        txtCourseName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        lblRegion = new javax.swing.JLabel();
        txtRegion = new javax.swing.JTextField();
        lblLanguage = new javax.swing.JLabel();
        txtLanguage = new javax.swing.JTextField();
        lblTerm = new javax.swing.JLabel();
        radioFall = new javax.swing.JRadioButton();
        radioSpring = new javax.swing.JRadioButton();
        btnAddCourse = new javax.swing.JButton();
        lblSchedule = new javax.swing.JLabel();
        lblTerm1 = new javax.swing.JLabel();
        lblTerm2 = new javax.swing.JLabel();
        lblTerm3 = new javax.swing.JLabel();
        txtStartTime = new javax.swing.JTextField();
        txtEndTime = new javax.swing.JTextField();
        dropDownDay1 = new javax.swing.JComboBox<>();
        btnAddSchedule = new javax.swing.JToggleButton();

        lblAddCourse.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblAddCourse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddCourse.setText("Add a Course");

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblCourseName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCourseName.setText("Course Name:");

        lblDescription.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDescription.setText("Description:");

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        jScrollPane1.setViewportView(txtDescription);

        lblRegion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRegion.setText("Region:");

        lblLanguage.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLanguage.setText("Language:");

        lblTerm.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTerm.setText("Term:");

        buttonGroup1.add(radioFall);
        radioFall.setText("Fall");

        buttonGroup1.add(radioSpring);
        radioSpring.setText("Spring");

        btnAddCourse.setText("Add Course");
        btnAddCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCourseActionPerformed(evt);
            }
        });

        lblSchedule.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblSchedule.setText("Schedule:");

        lblTerm1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTerm1.setText("Days:");

        lblTerm2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTerm2.setText("Start Time:");

        lblTerm3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTerm3.setText("End Time:");

        dropDownDay1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday" }));

        btnAddSchedule.setText("Add to Schedule");
        btnAddSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddScheduleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAddCourse, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTerm3)
                    .addComponent(lblTerm2)
                    .addComponent(lblTerm1)
                    .addComponent(lblSchedule)
                    .addComponent(lblTerm)
                    .addComponent(lblLanguage)
                    .addComponent(lblRegion)
                    .addComponent(lblDescription)
                    .addComponent(lblCourseName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                        .addComponent(txtCourseName, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtRegion, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtLanguage, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(radioFall)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(radioSpring))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtEndTime, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtStartTime, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dropDownDay1, javax.swing.GroupLayout.Alignment.LEADING, 0, 111, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addComponent(btnAddSchedule))))
                .addGap(153, 153, 153))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblAddCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnBack)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseName)
                    .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescription)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRegion))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLanguage))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioFall)
                    .addComponent(lblTerm)
                    .addComponent(radioSpring))
                .addGap(18, 18, 18)
                .addComponent(lblSchedule)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTerm1)
                    .addComponent(dropDownDay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTerm2)
                    .addComponent(txtStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTerm3)
                    .addComponent(txtEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddSchedule))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(btnAddCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        workArea.remove(this);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCourseActionPerformed
        UUID courseID = null;
        courseID = UUID.randomUUID();
        String courseName = txtCourseName.getText();
        String description = txtDescription.getText();
        String region = txtRegion.getText();
        String language = txtLanguage.getText();
        String term = radioFall.isSelected() ? "Fall" : "Spring";
        
        //TODO Validation
        Course course = coursesDirectory.addCourse();
        course.setCourseID("Course-"+courseID);
        course.setCourseName(courseName);
        course.setDescription(description);
        course.setProfessor(professor);
        course.setRegion(region);
        course.setLanguage(language);
        course.setTerm(term);
        course.setRating(0);
        course.setSchedule(schedule);
        
        
        JOptionPane.showMessageDialog(null,"Course Added Successfully!");
        
        txtCourseName.setText("");
        txtDescription.setText("");
        txtRegion.setText("");
        txtLanguage.setText("");
        radioFall.setSelected(false);
        radioSpring.setSelected(false);
        
    }//GEN-LAST:event_btnAddCourseActionPerformed

    private void btnAddScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddScheduleActionPerformed
        String day1 = dropDownDay1.getSelectedItem().toString();
        String startTime = txtStartTime.getText();
        String endTime = txtEndTime.getText();
        
        schedule.addDaySchedule(new DaySchedule(day1, startTime, endTime));
        
        JOptionPane.showMessageDialog(null, "Course Schedule Added!");
        
        dropDownDay1.setSelectedItem("Monday");
        txtStartTime.setText("");
        txtEndTime.setText("");
    }//GEN-LAST:event_btnAddScheduleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCourse;
    private javax.swing.JToggleButton btnAddSchedule;
    private javax.swing.JButton btnBack;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> dropDownDay1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddCourse;
    private javax.swing.JLabel lblCourseName;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblLanguage;
    private javax.swing.JLabel lblRegion;
    private javax.swing.JLabel lblSchedule;
    private javax.swing.JLabel lblTerm;
    private javax.swing.JLabel lblTerm1;
    private javax.swing.JLabel lblTerm2;
    private javax.swing.JLabel lblTerm3;
    private javax.swing.JRadioButton radioFall;
    private javax.swing.JRadioButton radioSpring;
    private javax.swing.JTextField txtCourseName;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtEndTime;
    private javax.swing.JTextField txtLanguage;
    private javax.swing.JTextField txtRegion;
    private javax.swing.JTextField txtStartTime;
    // End of variables declaration//GEN-END:variables
}
