/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Business.CoursesDirectory;
import Business.StudentDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Aayush
 */
public class RequestForFinancialAid extends javax.swing.JPanel {

    
         private JPanel workArea;
      private CoursesDirectory coursesDirectory;
      private StudentDirectory studentDirectory;
    /**
     * Creates new form RequestForFinancialAid
     */
    public RequestForFinancialAid(JPanel workArea,CoursesDirectory coursesDirectory,StudentDirectory studentDirectory) {
        initComponents();
                this.workArea = workArea;
        this.coursesDirectory =  coursesDirectory;
        this.studentDirectory = studentDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRequestForFinancialAid = new javax.swing.JLabel();
        btnBackRequestForFinancialAid = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCoursesSelectedForFinancialAid = new javax.swing.JTable();

        lblRequestForFinancialAid.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblRequestForFinancialAid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRequestForFinancialAid.setText("Request for Financial Aid");

        btnBackRequestForFinancialAid.setText("<<Back");
        btnBackRequestForFinancialAid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackRequestForFinancialAidActionPerformed(evt);
            }
        });

        tblCoursesSelectedForFinancialAid.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Course Name", "Description", "Professor", "Region", "Semester", "Language", "Rating"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCoursesSelectedForFinancialAid);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnBackRequestForFinancialAid, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRequestForFinancialAid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRequestForFinancialAid, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBackRequestForFinancialAid, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(275, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackRequestForFinancialAidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackRequestForFinancialAidActionPerformed
        // TODO add your handling code here:
        workArea.remove(this);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_btnBackRequestForFinancialAidActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackRequestForFinancialAid;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRequestForFinancialAid;
    private javax.swing.JTable tblCoursesSelectedForFinancialAid;
    // End of variables declaration//GEN-END:variables
}
