/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Business.Student;
import Business.StudentDirectory;
import javax.swing.JPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Ayush
 */
public class ReviewFinancialAidJPanel extends javax.swing.JPanel {
    
        private StudentDirectory studentDirectory;
        private JPanel workArea;

    /**
     * Creates new form ReviewFinancialAidJPanel
     */
    public ReviewFinancialAidJPanel(JPanel workArea  ,StudentDirectory studentDirectory) {
        initComponents();
        this.workArea = workArea;
        this.studentDirectory = studentDirectory;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblReviewFinancialAid = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReviewFinancialAid = new javax.swing.JTable();
        lblName = new javax.swing.JLabel();
        lblNameValue = new javax.swing.JLabel();
        btnView = new javax.swing.JButton();
        lblGrantFinancialAid = new javax.swing.JLabel();
        rdBtnYes = new javax.swing.JRadioButton();
        rdBtnNo = new javax.swing.JRadioButton();
        btnGrant = new javax.swing.JButton();
        btnBackRequestForFinancialAid = new javax.swing.JButton();

        lblReviewFinancialAid.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblReviewFinancialAid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReviewFinancialAid.setText("Review Financial Aid");

        tblReviewFinancialAid.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Student Name", "Student Username", "Student Email", "Aid Requested", "Reason", "Student Id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblReviewFinancialAid);

        lblName.setText("Name :");

        lblNameValue.setText("                         ");

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        lblGrantFinancialAid.setText("Financial Aid Granted :");

        buttonGroup1.add(rdBtnYes);
        rdBtnYes.setText("Yes");

        buttonGroup1.add(rdBtnNo);
        rdBtnNo.setText("No");

        btnGrant.setText("Grant");
        btnGrant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrantActionPerformed(evt);
            }
        });

        btnBackRequestForFinancialAid.setText("<<Back");
        btnBackRequestForFinancialAid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackRequestForFinancialAidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblReviewFinancialAid, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblGrantFinancialAid)
                                    .addComponent(lblName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNameValue)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnView))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(rdBtnNo)
                                                .addComponent(rdBtnYes))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addComponent(btnGrant)))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnBackRequestForFinancialAid)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblReviewFinancialAid, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(lblNameValue)
                    .addComponent(btnView))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGrantFinancialAid)
                    .addComponent(rdBtnYes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdBtnNo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGrant)
                .addGap(18, 18, 18)
                .addComponent(btnBackRequestForFinancialAid)
                .addContainerGap(168, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:

        int selectedRow = tblReviewFinancialAid.getSelectedRow();

        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null,"Please select a row from table first to view details", "Warning",JOptionPane.WARNING_MESSAGE);
        } else {
            DefaultTableModel model = (DefaultTableModel) tblReviewFinancialAid.getModel();

            String studentName = (String) model.getValueAt(selectedRow, 0);

            lblNameValue.setText(studentName);

            boolean financialAidRequested = (boolean) model.getValueAt(selectedRow,3);

            if(financialAidRequested){
                rdBtnNo.setSelected(true);
            }
            else{
                rdBtnYes.setSelected(false);
            }
        }
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnGrantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrantActionPerformed
        // TODO add your handling code here:
        if("".equals(lblNameValue.getText())) {
            JOptionPane.showMessageDialog(null,"Please select a student");
        }
        else {
            int selectedRow = tblReviewFinancialAid.getSelectedRow();

            DefaultTableModel model = (DefaultTableModel) tblReviewFinancialAid.getModel();

            String studentId = (String) model.getValueAt(selectedRow, 5);

            Student student = studentDirectory.searchStudentByStudentId(studentId);

            if(rdBtnYes.isSelected()){
                student.setFinancialAidGranted(true);
            }
            else{
                student.setFinancialAidGranted(false);
            }

            JOptionPane.showMessageDialog(null,"Financial Aid Granted!");

            lblNameValue.setText("");
            rdBtnNo.setSelected(true);
            populateTable();
        }
    }//GEN-LAST:event_btnGrantActionPerformed

    private void btnBackRequestForFinancialAidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackRequestForFinancialAidActionPerformed
        // TODO add your handling code here:
        workArea.remove(this);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_btnBackRequestForFinancialAidActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackRequestForFinancialAid;
    private javax.swing.JButton btnGrant;
    private javax.swing.JButton btnView;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGrantFinancialAid;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNameValue;
    private javax.swing.JLabel lblReviewFinancialAid;
    private javax.swing.JRadioButton rdBtnNo;
    private javax.swing.JRadioButton rdBtnYes;
    private javax.swing.JTable tblReviewFinancialAid;
    // End of variables declaration//GEN-END:variables

        private void populateTable(){
            System.out.println(studentDirectory.getStudentDirectory());
        DefaultTableModel dtm = (DefaultTableModel) tblReviewFinancialAid.getModel();
        dtm.setRowCount(0);
        for (Student student : studentDirectory.getStudentDirectory()){
           if(student.isFinancialAidRequested() && !student.isFinancialAidGranted()){
               Object[] row = new Object[6];
                row[0] = student.getStudentName();
                row[1] = student.getStudentUserName();
                row[2] = student.getStudentEmailID();
                row[3] = student.isFinancialAidRequested();
                row[4] = student.getFinancialAidReason();
                row[5] = student.getStudentID();
                dtm.addRow(row);         
            }
        }
    }
}
