/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Business.Course;
import Business.CoursesDirectory;
import Business.Student;
import Business.StudentDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aayush
 */
public class StudentViewCoursesJPanel extends javax.swing.JPanel {
    
      private JPanel workArea;
      private CoursesDirectory coursesDirectory;
      private StudentDirectory studentDirectory;
      private Student student;

    /**
     * Creates new form StudentViewCoursesJPanel
     */
    public StudentViewCoursesJPanel(JPanel workArea,CoursesDirectory coursesDirectory,StudentDirectory studentDirectory, Student student) {
        initComponents();        
        this.workArea = workArea;
        this.coursesDirectory =  coursesDirectory;
        this.studentDirectory = studentDirectory;
        this.student = student;
        populateTable();
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblViewCoursesSelected = new javax.swing.JLabel();
        btnBackViewCourses = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblViewCoursesSelected = new javax.swing.JTable();
        txtProfessorViewCourses = new javax.swing.JTextField();
        lblRegion = new javax.swing.JLabel();
        lblRatingSelectCourses = new javax.swing.JLabel();
        txtRegionViewCourses = new javax.swing.JTextField();
        txtRatingViewCourse = new javax.swing.JTextField();
        txtLanguageViewCourses = new javax.swing.JTextField();
        lblLanguage = new javax.swing.JLabel();
        lblCourseName = new javax.swing.JLabel();
        lblSemester = new javax.swing.JLabel();
        txtCourseNameViewCourses = new javax.swing.JTextField();
        radioFallViewCourses = new javax.swing.JRadioButton();
        lblDescription = new javax.swing.JLabel();
        radioSpringViewCourses = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaDescriptionViewCourses = new javax.swing.JTextArea();
        lblProfessor = new javax.swing.JLabel();
        btnViewCourses = new javax.swing.JButton();
        btnCompleteCourse = new javax.swing.JButton();

        lblViewCoursesSelected.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblViewCoursesSelected.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewCoursesSelected.setText("View Courses");

        btnBackViewCourses.setText("<<Back");
        btnBackViewCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackViewCoursesActionPerformed(evt);
            }
        });

        tblViewCoursesSelected.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Course ID", "Course Name", "Description", "Professor", "Region", "Semester", "Language", "Rating"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblViewCoursesSelected);

        lblRegion.setText("Region");

        lblRatingSelectCourses.setText("Rating");

        txtRatingViewCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRatingViewCourseActionPerformed(evt);
            }
        });

        lblLanguage.setText("Language");

        lblCourseName.setText("Course Name");

        lblSemester.setText("Semester");

        radioFallViewCourses.setText("Fall");

        lblDescription.setText("Description");

        radioSpringViewCourses.setText("Spring");

        txtAreaDescriptionViewCourses.setColumns(20);
        txtAreaDescriptionViewCourses.setRows(5);
        jScrollPane2.setViewportView(txtAreaDescriptionViewCourses);

        lblProfessor.setText("Professor");

        btnViewCourses.setText("View");
        btnViewCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCoursesActionPerformed(evt);
            }
        });

        btnCompleteCourse.setText("Complete");
        btnCompleteCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteCourseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnBackViewCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblViewCoursesSelected, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblLanguage)
                                    .addComponent(lblRegion)
                                    .addComponent(lblProfessor)
                                    .addComponent(lblSemester)
                                    .addComponent(lblRatingSelectCourses))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtLanguageViewCourses)
                            .addComponent(txtRegionViewCourses)
                            .addComponent(txtCourseNameViewCourses)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radioFallViewCourses)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(radioSpringViewCourses))
                            .addComponent(txtRatingViewCourse)
                            .addComponent(txtProfessorViewCourses)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addComponent(btnViewCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnCompleteCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblViewCoursesSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBackViewCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCourseNameViewCourses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewCourses)
                    .addComponent(btnCompleteCourse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescription)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProfessor)
                    .addComponent(txtProfessorViewCourses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegion)
                    .addComponent(txtRegionViewCourses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLanguage)
                    .addComponent(txtLanguageViewCourses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSemester)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radioSpringViewCourses)
                        .addComponent(radioFallViewCourses)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRatingViewCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRatingSelectCourses))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackViewCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackViewCoursesActionPerformed
        // TODO add your handling code here:
        workArea.remove(this);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
        populateTable();
    }//GEN-LAST:event_btnBackViewCoursesActionPerformed

    private void txtRatingViewCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRatingViewCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRatingViewCourseActionPerformed

    private void btnViewCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCoursesActionPerformed
        // TODO add your handling code here:

        int selectedRow = tblViewCoursesSelected.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null,"Please select a row from table first to view details", "Warning",JOptionPane.WARNING_MESSAGE);
        } else {
            DefaultTableModel model = (DefaultTableModel) tblViewCoursesSelected.getModel();
            
            String courseID = (String) model.getValueAt(selectedRow, 0);
            String courseName = (String) model.getValueAt(selectedRow, 1);
            String description = (String) model.getValueAt(selectedRow, 2);
            String professor = (String) model.getValueAt(selectedRow,3);
            String region = (String) model.getValueAt(selectedRow, 4);

            String term = (String) model.getValueAt(selectedRow, 5);
            String language = (String) model.getValueAt(selectedRow, 6);
            Double rating = (Double) model.getValueAt(selectedRow, 7);

            txtCourseNameViewCourses.setText(courseName);
            txtAreaDescriptionViewCourses.setText(description);
            txtRegionViewCourses.setText(region);
            txtLanguageViewCourses.setText(language);
            txtProfessorViewCourses.setText(professor);
            txtRatingViewCourse.setText(rating.toString());

            if(term == "Fall") {
                radioFallViewCourses.setSelected(true);
                radioSpringViewCourses.setSelected(false);
            } else {
                radioFallViewCourses.setSelected(false);
                radioSpringViewCourses.setSelected(true);
            }
        }
    }//GEN-LAST:event_btnViewCoursesActionPerformed

    private void btnCompleteCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteCourseActionPerformed
         int selectedRow = tblViewCoursesSelected.getSelectedRow();
         DefaultTableModel model = (DefaultTableModel) tblViewCoursesSelected.getModel();

            String courseID = (String) model.getValueAt(selectedRow, 0);
            for(Course course : student.getStudentCourseDirectory()) {
                if(courseID == course.getCourseID()) {
                    course.setIsCompleted(true);
                }
            }
            
         JOptionPane.showMessageDialog(null, "Course Completed Successful!");
            
            
    }//GEN-LAST:event_btnCompleteCourseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackViewCourses;
    private javax.swing.JButton btnCompleteCourse;
    private javax.swing.JButton btnViewCourses;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCourseName;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblLanguage;
    private javax.swing.JLabel lblProfessor;
    private javax.swing.JLabel lblRatingSelectCourses;
    private javax.swing.JLabel lblRegion;
    private javax.swing.JLabel lblSemester;
    private javax.swing.JLabel lblViewCoursesSelected;
    private javax.swing.JRadioButton radioFallViewCourses;
    private javax.swing.JRadioButton radioSpringViewCourses;
    private javax.swing.JTable tblViewCoursesSelected;
    private javax.swing.JTextArea txtAreaDescriptionViewCourses;
    private javax.swing.JTextField txtCourseNameViewCourses;
    private javax.swing.JTextField txtLanguageViewCourses;
    private javax.swing.JTextField txtProfessorViewCourses;
    private javax.swing.JTextField txtRatingViewCourse;
    private javax.swing.JTextField txtRegionViewCourses;
    // End of variables declaration//GEN-END:variables

        private void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel) tblViewCoursesSelected.getModel();
        dtm.setRowCount(0);
        for (Course course : student.getStudentCourseDirectory()){
            Object[] row = new Object[8];
            row[0] = course.getCourseID();
            row[1] = course.getCourseName();
            row[2] = course.getDescription();
            row[3] = course.getProfessor().getProfessorName();
            row[4] = course.getRegion();
            row[5] = course.getTerm();
            row[6] = course.getLanguage();
            row[7] = course.getRating();
            
            dtm.addRow(row);
            
        }
    }

}
