/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Business.Broker;
import Business.BrokerDirectory;
import Business.University;
import Business.UniversityDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author admin
 */
public class UniversityJPanel extends javax.swing.JPanel {
     private JPanel workArea;
    private UniversityDirectory universityDirectory;
    private University university;
    /**
     * Creates new form UniverisityJPanel
     */
    UniversityJPanel(JPanel workArea, UniversityDirectory universityDirectory, University university) {
        initComponents();
        this.workArea = workArea;
        this.universityDirectory = universityDirectory;
        this.university = university;
        
        lblUniversityTiltle.setText("Welcome " + university.getUniversityName().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUniversityTiltle = new javax.swing.JLabel();
        btnContactCampusConnect = new javax.swing.JButton();
        btnViewAnalytics = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(223, 223, 223));

        lblUniversityTiltle.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        lblUniversityTiltle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUniversityTiltle.setText("Hello University");

        btnContactCampusConnect.setBackground(new java.awt.Color(0, 0, 0));
        btnContactCampusConnect.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        btnContactCampusConnect.setForeground(new java.awt.Color(255, 255, 255));
        btnContactCampusConnect.setText("Share  Insight");
        btnContactCampusConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContactCampusConnectActionPerformed(evt);
            }
        });

        btnViewAnalytics.setBackground(new java.awt.Color(0, 0, 0));
        btnViewAnalytics.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        btnViewAnalytics.setForeground(new java.awt.Color(255, 255, 255));
        btnViewAnalytics.setText("View Analytics");
        btnViewAnalytics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAnalyticsActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        jButton3.setText("<< Log Out");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(214, Short.MAX_VALUE)
                .addComponent(btnContactCampusConnect, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewAnalytics, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(217, 217, 217))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUniversityTiltle, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUniversityTiltle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnContactCampusConnect, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewAnalytics, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 318, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnContactCampusConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContactCampusConnectActionPerformed
        // TODO add your handling code here:
        ContactCampusConnectJPanel contactCampusConnectJPanel = new ContactCampusConnectJPanel( workArea,  university, universityDirectory);
        workArea.add("ContactCampusConnectJPanel",contactCampusConnectJPanel );
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);

    }//GEN-LAST:event_btnContactCampusConnectActionPerformed

    private void btnViewAnalyticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAnalyticsActionPerformed
        // TODO add your handling code here:
//        ChartDisplay chartDisplay = new ChartDisplay();
//        workArea.add("chartDisplay", chartDisplay);
//        CardLayout layout = (CardLayout) workArea.getLayout();
//        layout.next(workArea);
        DisplayUniversityInsightData displayUniversityInsightData = new DisplayUniversityInsightData( workArea,  university, universityDirectory);
                workArea.add("DisplayUniversityInsightData",displayUniversityInsightData );
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);

    }//GEN-LAST:event_btnViewAnalyticsActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        workArea.remove(this);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContactCampusConnect;
    private javax.swing.JButton btnViewAnalytics;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel lblUniversityTiltle;
    // End of variables declaration//GEN-END:variables
}
